#!/bin/bash

SAMPLE_RATE=$1
BIT_DEPTH=$2

if [ -z "$SAMPLE_RATE" ]; then
  SAMPLE_RATE=48000
fi

if [ -z "$BIT_DEPTH" ]; then
  BIT_DEPTH=8
fi

CFLAGS="-DSAMPLE_RATE=$SAMPLE_RATE -DBIT_DEPTH=$BIT_DEPTH"

g++ main.cpp -o main $CFLAGS
if [ $? -ne 0 ]; then
  echo "Error while compiling."
  exit $?
fi
./main | pacat --format=u$BIT_DEPTH --rate=$SAMPLE_RATE --channels=1 --raw

#sox -r $SAMPLE_RATE -e unsigned -b 8 -c 1 main.raw main.wav
#play main.wav
